# CAN ONLY BE ENABLED ONCE QUOTA IS UPPED
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: redishop-ingress
#   namespace: default
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /users/*
#         backend:
#           serviceName: users
#           servicePort: 80
#       - path: /orders/*
#         backend:
#           serviceName: orders
#           servicePort: 80
#       - path: /stock/*
#         backend:
#           serviceName: stock
#           servicePort: 80
#       - path: /stock/*
#         backend:
#           serviceName: payments
#           servicePort: 80
# ---
apiVersion: v1
kind: Service
metadata:
  name: users
  namespace: default
  # annotations:
    # cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: users
---
apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: default
  # annotations:
    # cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: orders
---
apiVersion: v1
kind: Service
metadata:
  name: stock
  namespace: default
  # annotations:
    # cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: stock
---
apiVersion: v1
kind: Service
metadata:
  name: payments
  namespace: default
  # annotations:
  #   cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: payments
