apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: eu.gcr.io/nice-script-280016/redishop
        ports:
        - containerPort: 8000
        env:
          # - name: REDIS_URL
            # value: "redistestingurl"
          - name: SERVICE
            value: "stock"
          - name: BACKEND
            value: "redis"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stock
  template:
    metadata:
      labels:
        app: stock
    spec:
      containers:
      - name: stock
        image: eu.gcr.io/nice-script-280016/redishop
        ports:
        - containerPort: 8000
        env:
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: POSTGRES_DB
            value: redi
          - name: service
            value: stock
          - name: backend
            value: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: eu.gcr.io/nice-script-280016/redishop
        ports:
        - containerPort: 8000
        env:
          - name: service
            value: stock
          - name: backend
            value: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - name: payments
        image: eu.gcr.io/nice-script-280016/redishop
        ports:
        - containerPort: 8000
        env:
          # - name: "URL_USER"
            # value: "TODO: CHANGE TO VALUE"
          - name: service
            value: stock
          - name: backend
            value: redis
